Vagrant.configure("2") do |config|

  config.vm.define :stacknext do |stacknext|
    stacknext.vm.box = "generic/fedora27"
    stacknext.vm.network :private_network, bridge: "wlp61s0", ip: "3.2.1.10"
    stacknext.vm.hostname = "stacknext"
  end

  config.vm.define :mongodb do |mongodb|
    mongodb.vm.box = "generic/fedora27"
    mongodb.vm.network :private_network, bridge: "wlp61s0", ip: "3.2.1.11"
    mongodb.vm.hostname = "mongodb"
  end

end
