---
- hosts: localhost
  name: Install StackNext Desktop on localhost
  become: yes
  vars:
    repo_url: https://github.com/rcpage/desktop.git
  tasks:

    - name: "Downloading...{{ repo_url }}"
      git:
        repo: "{{ repo_url }}"
        dest: ./

    - name: Install the latest version of NodeJS
      yum:
        name: nodejs
        state: latest
        